In [1]:
%matplotlib inline
import numpy as np
import pandas as pd
np.random.seed(123)

In [2]:
# How likely is it that you roll doubles when rolling two dice?

In [3]:
6/36

0.16666666666666666

In [4]:
# If you flip 8 coins, what is the probability of getting exactly 3 heads? What is the probability of getting more than 3 heads?

In [5]:
attempts = 10000
coins = 8
heads = 1
tails = 0
outcomes =[heads, tails]

In [6]:
flips= np.random.choice(outcomes, size =(attempts, coins))
flips

array([[1, 0, 1, ..., 1, 1, 0],
       [0, 1, 0, ..., 0, 1, 0],
       [1, 0, 0, ..., 1, 0, 0],
       ...,
       [0, 0, 1, ..., 1, 0, 1],
       [0, 1, 1, ..., 0, 0, 1],
       [0, 0, 0, ..., 0, 0, 0]])

In [7]:
num_heads = flips.sum(axis=1)
num_heads

array([6, 3, 4, ..., 4, 4, 1])

In [8]:
calculated_prob=(num_heads == 3).mean()
calculated_prob

0.2105

In [9]:
calculated_prob=(num_heads > 3).mean()
calculated_prob

0.6441

In [10]:
# There are approximitely 3 web development cohorts for every 1 data science cohort at Codeup. Assuming that Codeup randomly selects an alumni to put on a billboard, what are the odds that the two billboards I drive past both have data science students on them?

In [11]:
(1/4) * (1/4)

0.0625

In [12]:
# Codeup students buy, on average, 3 poptart packages with a standard deviation of 1.5 a day from the snack vending machine. If on monday the machine is restocked with 17 poptart packages, how likely is it that I will be able to buy some poptarts on Friday afternoon?

In [13]:
poptart_avg = 3
poptart_std = 1.5
days= 5
attempts = 1000000

In [14]:
simulated_consumed_poptarts= np.random.normal(poptart_avg, poptart_std,(attempts, days))
simulated_consumed_poptarts

array([[3.10412472e+00, 2.67613939e+00, 3.28060569e+00, 3.53714534e+00,
        3.18549210e+00],
       [4.43539613e+00, 1.78860610e+00, 2.48253820e+00, 4.27565742e+00,
        3.82770460e+00],
       [2.94494993e+00, 4.82192615e+00, 7.75398311e-01, 2.81844442e+00,
        3.62907901e+00],
       ...,
       [3.28702571e+00, 1.59576889e+00, 4.79511587e+00, 3.34092211e+00,
        2.26902541e+00],
       [3.78521388e+00, 1.85763166e+00, 2.88859738e+00, 1.30692875e+00,
        4.10026705e+00],
       [3.00026822e-03, 5.36621890e+00, 4.04940970e+00, 2.96696749e+00,
        2.61213705e+00]])

In [15]:
calculated_prob = (simulated_consumed_poptarts.sum(axis=1) <17).mean()
calculated_prob

0.72389

In [16]:
poptart_packs = 17 
days = 5 
attempts = 10000 

In [17]:
packages = np.round(np.random.normal(3,1.5, (attempts, days)))
packages

array([[ 2.,  5.,  4.,  3.,  2.],
       [ 3.,  4.,  4.,  1.,  3.],
       [ 0.,  4.,  5.,  3.,  1.],
       ...,
       [ 0.,  3.,  4.,  3., -1.],
       [ 5.,  1.,  4.,  2.,  2.],
       [ 3.,  5.,  5.,  3.,  4.]])

In [18]:
package_purchased = np.where(packages < 0,0,packages)
package_purchased

array([[2., 5., 4., 3., 2.],
       [3., 4., 4., 1., 3.],
       [0., 4., 5., 3., 1.],
       ...,
       [0., 3., 4., 3., 0.],
       [5., 1., 4., 2., 2.],
       [3., 5., 5., 3., 4.]])

In [19]:
all_packages = package_purchased.sum(axis=1)
all_packages

array([16., 15., 13., ..., 10., 14., 20.])

In [20]:
friday = all_packages < 17
friday

array([ True,  True,  True, ...,  True,  True, False])

In [21]:
left_on_friday = friday.mean()
left_on_friday

0.6612

In [22]:
# If a man and woman are chosen at random, what is the likelihood the woman is taller than the man?

In [23]:
men_avg= 178
men_std=8
women_avg=170
women_std=6
trials = 1000000

In [24]:
men = np.random.normal(men_avg, men_std, attempts)
women = np.random.normal(women_avg, women_std, attempts)
calculated_prob = (women > men).mean()
calculated_prob

0.211

In [25]:
# What are the odds that after having 50 students download anaconda, no one has an installation issue? 100 students?

In [26]:
attempts= 1000000
installs= 50
conda_fails= 1
success = 0
outcomes= [conda_fails, success]
failure= 1/250

In [27]:
installs = np.random.choice(outcomes, size = (attempts, installs), p = [249/250, 1/250])
((installs < failure).sum(axis=1)== 0).mean()

0.818725

In [28]:
(installs.sum(axis = 1) == 0).mean()

0.0

In [29]:
((installs < failure).sum(axis=1)== 0).mean()

0.818725

In [30]:
n_trials= 1000000
n_installs= 100
conda_fails= 1
success = 0
prob_fail= 1/250

In [31]:
installs_100 = np.random.choice(outcomes, size = (attempts, installs), p = [249/250, 1/250])
((installs_100 < failure).sum(axis=1)== 0).mean()

/usr/local/anaconda3/lib/python3.10/site-packages/numpy/core/fromnumeric.py:86: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)


ValueError: setting an array element with a sequence.

In [ ]:
attemptss= 1000000
installs= 150
conda_fails= 1
success = 0
failure= 1/250

In [ ]:
installs = np.random.random((installs,attempts))
installs < failure

In [ ]:
((installs < failure).sum(axis=1)> 0).mean()

In [ ]:
attempts= 1000000
installs= 450
conda_fails= 1
success = 0
failure= 1/250

In [ ]:
installs = np.random.random((installs,attempts))

In [ ]:
installs < failure

In [ ]:
((installs < failure).sum(axis=1)== 0).mean()

In [ ]:
# There's a 70% chance on any given day that there will be at least one food truck at Travis Park. However, you haven't seen a food truck there in 3 days. How unlikely is this?

In [ ]:
rows= 1000000
columns= 3
truck=1
no_truck=0
data= np.random.random((rows,columns))
truck_prob = 0.7

In [ ]:
((data < truck_prob).sum(axis=1)==0).mean()

In [ ]:
rows= 1000000
columns= 2 
truck=1
no_truck=0
truck_prob = 0.7
days = np.random.random((rows,columns))

In [ ]:
calculated_prob= ((days < truck_prob).sum(axis=1) >0).mean()
calculated_prob

In [ ]:
# If 23 people are in the same room, what are the odds that two of them share a birthday? What if it's 20 people? 40?

In [ ]:
outcomes = range(0, 365)
people= 23 
attempts= 1000000 

In [ ]:
bd = np.random.choice(outcomes, size=(attempts, people))
bd

In [ ]:
pd.DataFrame(bd).nunique(axis = 1)

In [ ]:
(pd.DataFrame(bd).nunique(axis = 1) < 23).mean()

In [ ]:
attempts = 100000
people = 20
outcomes = range(0, 365) 

In [ ]:
birthdays = np.random.choice(outcomes, size=(attempts, people))
birthdays

In [ ]:
df = pd.DataFrame(birthdays)
df.head()

In [ ]:
df["n_unique"] = df.nunique(axis=1)
df.head()

In [ ]:
(df.n_unique != people).mean()

In [ ]:
attempts = 100000
people = 40
outcomes = range(0, 365) 

In [ ]:
birthdays = np.random.choice(outcomes, size=(attempts, people))
birthdays

In [ ]:
df = pd.DataFrame(birthdays)
df.head()

In [ ]:
df["n_unique"] = df.nunique(axis=1)
df.head()

In [ ]:
(df.n_unique != people).mean()